# Generated by Django 5.2.2 on 2025-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
